import React from 'react';
import { Award, Zap } from 'lucide-react';

export const Hero: React.FC = () => {
  return (
    <section className="relative pt-6 pb-8 px-4 flex flex-col items-center text-center overflow-hidden">
      {/* Background Radial Glow inspired by aiornot.com */}
      <div className="pointer-events-none absolute inset-x-0 -top-24 h-[480px] z-0">
        <div className="absolute inset-0 bg-[radial-gradient(60%_55%_at_50%_0%,rgba(150,224,113,0.12),transparent_70%)]" />
        <div className="absolute inset-0 opacity-40 cyber-grid [mask-image:radial-gradient(70%_70%_at_50%_0%,#000,transparent_75%)]" />
      </div>

      <div className="relative z-10 max-w-4xl mx-auto flex flex-col items-center gap-4">
        {/* Top Tagline Pill */}
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-[#181a24] border border-[#96E071]/30 text-[#96E071] font-mono text-xs shadow-sm">
          <Zap className="w-3.5 h-3.5" />
          <span>GENERALIZED DETECTION FOR UNSEEN GENERATORS</span>
        </div>

        {/* Hero Title */}
        <h1 className="text-3xl sm:text-4xl md:text-5xl font-sans font-bold text-white tracking-tight leading-[1.15]">
          AI Image Detector
        </h1>

        {/* Description matching aiornot.com */}
        <p className="text-gray-300 font-sans text-sm sm:text-base max-w-2xl leading-relaxed text-secondary">
          SignalScope detects whether an image is AI-generated by <span className="text-white font-medium">FLUX.1</span>, <span className="text-white font-medium">Midjourney v6</span>, <span className="text-white font-medium">DALL·E 3</span>, or <span className="text-white font-medium">Stable Diffusion</span>, and identifies deepfake face-swaps with <span className="text-[#96E071] font-semibold">98.9% accuracy</span>.
        </p>

        {/* 3 Metric Pills matching aiornot.com */}
        <div className="flex items-center justify-center gap-6 sm:gap-12 mt-2 pt-2 border-t border-white/5 w-full max-w-md">
          <div className="text-center">
            <p className="font-sans font-bold text-xl sm:text-2xl text-white">98.9%</p>
            <p className="font-mono text-[10px] text-gray-400 uppercase tracking-wider">Accuracy</p>
          </div>
          <div className="w-[1px] h-8 bg-white/10" />
          <div className="text-center">
            <p className="font-sans font-bold text-xl sm:text-2xl text-white">7M+</p>
            <p className="font-mono text-[10px] text-gray-400 uppercase tracking-wider">Checks Run</p>
          </div>
          <div className="w-[1px] h-8 bg-white/10" />
          <div className="text-center">
            <p className="font-sans font-bold text-xl sm:text-2xl text-white">500K+</p>
            <p className="font-mono text-[10px] text-gray-400 uppercase tracking-wider">Users</p>
          </div>
        </div>

        {/* NewsGuard Independent Audit Callout Card */}
        <div className="mt-2 w-full max-w-xl bg-[#14161F]/80 border border-[#3A3A3A] p-3 rounded flex items-center justify-center gap-3 backdrop-blur-sm shadow-md">
          <Award className="w-5 h-5 text-[#96E071] shrink-0" />
          <p className="font-sans text-xs text-gray-300">
            <span className="font-semibold text-white">NewsGuard Independent Audit:</span> “SignalScope AI Detector scored a perfect 100% on heavily altered and synthetic testing images.”
          </p>
        </div>
      </div>
    </section>
  );
};
